### ISSUE TITLE
You can place building over troops in MapEd

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#100]
Repro steps:

1.- Start the game.
2.- Create a new map in MapEd.
3.- Click Village planning > units.
4.- Select any soldier.
5.- Add units and columns (i.e. 5x5 troop).
6.- Click Village planning > houses.
7.- Select any building.
8.- Place it over troop.

Result: building is placed over the troop. 

![imagen](https://user-images.githubusercontent.com/36303894/52900442-84a8e600-31d4-11e9-8895-8de342b3462e.png)

**Comment by Kromster80** [comment]
What would be desired behaviour, disallowing to place house over group leader?

**Comment by LpTrip** [comment]
I'd rather say disallowing house placement over any unit (soldier or serf).

**Comment by Kromster80** [comment]
Except for virtual group members, who get sutoplaced on gamestart. Okay )

**Comment by Kromster80** [comment]
Might also add a warning on map open in MapEd about overlapping units/houses.

**Comment by Kromster80** [comment]
Houses can be placed over virtual group members, since they get autoplaced on mission start.
Warning seems not needed.
