### ISSUE TITLE
Woodcutter can plant trees in building layout

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#102]
Repro steps:

1.- Start the game.
2.- Build a woodcutter's hut and train a woodcutter, preferably in an open area with no trees.
3.- When it starts to plant a tree, place a building layout over it.
4.- Make your workers complete the building.
5.- Let time go by.

Result: tree is planted and it starts to grow "inside" the building. If the building is destroyed, tree remains and can be chopped down.

![imagen](https://user-images.githubusercontent.com/36303894/53166564-6a944c80-35b4-11e9-9485-85dc8537da58.png)

**Comment by Kromster80** [comment]
Fixed in r8556+
