### ISSUE TITLE
Orchard suddenly appears before receiveing wood

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#103]
Repro steps:

1.- Start the game.
2.- Be sure to have no wood and train a laborer.
3.- Lay out an orchard.

Result: laborer starts to dig, and when the animation finishes, apple tree suddenly pops up. If enough time goes by, apple start to appear (and mature) in the tree.

Maybe tree popping up would be "ok", but perhaps fences shouldn't appear until wood arrives?

![imagen](https://user-images.githubusercontent.com/36303894/53167108-cb705480-35b5-11e9-945a-1b8d1f1ada04.png)

**Comment by Kromster80** [comment]
Fixed orchards to appear after builder gets wood and fixed initial stage to "no apples yet".
Completed: At revision: 7665
