### ISSUE TITLE
"Prologue" mission can be won without completing all objectives

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#105]
Repro steps:

1.- Start the game
2.- Play DarkianMaker campaign, mission Prologue.
3.- Let initial assault to the bridge go by.
4.- Sneak around with your knights and at least one crossbowman to King Rodewic's position.
5.- Have your crossbowman lure guarding knights around the king.
6.- Attack king with your 6 horseman.

Result: altought "defend the bridge" and "destroy Clan Uberk and Tamark" and objectives haven't been completed (for some reason, it automatically appears as completed), you achieve victory by completing last objective. 

![imagen](https://user-images.githubusercontent.com/36303894/53176555-147fd300-35cd-11e9-8fac-d8ba01585859.png)

**Comment by DarkianMaker** [comment]
This has been reported before and is on the to-do list of script reworks for that mission.

It is intended if you ignore the other two objectives that obviously the enemy armies retreat canonically but the real consequences of that can't be implemented in the campaign yet.

**Comment by LpTrip** [comment]
Actually the enemy armies advanced on the bridge and razed both towns to the ground! I was thinking to file a report because first objective "defend the bridge" can't be failed, but I think is all related to this script rework pending.

**Comment by DarkianMaker** [comment]
Yeah, previous time we ran into a report on it was still on the Discord server so no worries.

@Kromster80 can you get the labels going on this? It's going to be fixed in the next campaign update

**Comment by Kromster80** [comment]
@DarkianMaker sorry for late reply. What labels would you like to see?

**Comment by DarkianMaker** [comment]
@Kromster80 
I'd say the following:
- 'severity: low'
- 'status: accepted'
- 'type: flaw'

**Comment by DarkianMaker** [comment]
This issue is fixed in the upcoming Campaign update and can be closed once that update hits.

**Comment by DuckingDuke** [comment]
Oh, this issue was fixed years ago. It can be closed
