### ISSUE TITLE
Options menu doesn't close when pressing Esc

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#108]
Repro steps:

1.- Start any game
2.- Open menu by clicking the button or pressing Esc.
3.- Click options.
4.- Press Esc.

Result: options menu doesn't close and game resumes in background. Presing Esc again will pause the game again bring menu out front.

![imagen](https://user-images.githubusercontent.com/36303894/53183416-fec4da80-35d9-11e9-8a39-e2a732c78750.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7652
