### ISSUE TITLE
EAssertionFailed: Normal mission path must have no \ in its mask

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#109]
Repro steps:

1.- Start the game.
2.- Open MapEd
3.- Click Menu >save map.
4.- Rename to `\`
5.- Press cancel.

Result: error appears. Bug report sent.

![imagen](https://user-images.githubusercontent.com/36303894/53186644-27e86980-35e0-11e9-8c6d-f7cf4583093e.png)

**Comment by LpTrip** [comment]
Related to this issue, you get another EAssertionFailed if you select campagin map, change name to "123" (for example) and press cancel.

Campaign mission path must have only one \ in its mask

![imagen](https://user-images.githubusercontent.com/36303894/53216314-eaf99280-3632-11e9-843c-07392c8bc438.png)

**Comment by Kromster80** [comment]
Seems to be fixed in r7662+
