### ISSUE TITLE
Single player appears listed twice in Save option in MapEd

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#110]
Repro steps:

1.- Start the game.
2.- Click on Map Editor.
3.- Click in Menu > save map.

Result: "Singleplayer" maps are listed twice. I think last option is for "Dev maps"

![imagen](https://user-images.githubusercontent.com/36303894/53191155-de048100-35e9-11e9-8845-129dc8ee28bc.png)

**Comment by Kromster80** [comment]
Looks like the text got clipped. 
Second one refers to Dev maps )
