### ISSUE TITLE
Infinite button appears Toggled on second workshop

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#112]
Repro steps:

1.- Start the game.
2.- Play any map from scratch.
3.- Build your base up until you unlock Weapons workshop.
4.- Build one workshop and toggle an infinite amount in any weapon.
5.- Build a second workshop and select it.

Result: infinite button of the weapon you ordered in first workshop appears as toggled on. You have to toggle off and toggle back on again to place the order. This issue occurs with every weapon and armor maker.

![imagen](https://user-images.githubusercontent.com/36303894/53218197-fa300e80-3639-11e9-9d8f-351e605981e1.png)

**Comment by Kromster80** [comment]
Made Inf button to update when changing selected house.

It is still a hack, toggling between 0 and 999 and being down when order is >500.
I intend to overhaul its design later on.
