### ISSUE TITLE
Metallurgist's ladle has no textures and flickers

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#114]
Repro steps:

1.- Start the game.
2.- Open MapEd.
3.- Place a metallurgist.

Result: metallurgist's ladle flickers and has no texture. This issue also occurs while playing a normal game and training a metallurgist, when walking from school to iron smithy or mint.

Explainatory GIF: https://giphy.com/gifs/vNg1poguX8sGkWiS18

This issue also causes some strange shadows appear over the map:

![imagen](https://user-images.githubusercontent.com/36303894/53240753-4bfa8800-367e-11e9-812e-b1f7d32df610.png)

**Comment by Kromster80** [comment]
Flickering seems to be fixed, but the ladle is still rendered closely under the ground surface. To be fixed.

**Comment by Kromster80** [comment]
Fixed somewhere in 09.2023
