### ISSUE TITLE
Cidermaker's model overlaps with roads

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#116]
Cidermaker's apple bucket is outside house "boundaries"

![imagen](https://user-images.githubusercontent.com/36303894/53249811-cf74a300-3697-11e9-8ab1-bc9ad30a4d8d.png)

This issue slightly happens with iron smithy aswell.

![imagen](https://user-images.githubusercontent.com/36303894/53249917-0945a980-3698-11e9-9e60-a103d6f0f290.png)

**Comment by Kromster80** [comment]
I'm thinking of making house around 15% smaller
