### ISSUE TITLE
Towers can't be placed in MapEd if no building is near

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#117]
Repro steps:

1.- Start the game.
2.- Create a new map in MapEd.
3.- Click Village planning > Houses.
4.- Select Watchtower or Bolt tower and try to place it anywhere.

Result: towers can't be placed alone. You need to place a building before. 

![imagen](https://user-images.githubusercontent.com/36303894/53250230-b9b3ad80-3698-11e9-8832-5754b874fa9d.png)

**Comment by DarkianMaker** [comment]
I think this is mostly because in the game itself you also need to be near buildings to place towers as well

**Comment by Kromster80** [comment]
True, but in MapEd thats easily "fixed" by placing a house, placing a Tower and then removing a house.
Hence no real leverage to enforce that rule in MapEd anyway. Besides map design might need astray Towers.

**Comment by Kromster80** [comment]
Allowed to place towers anywhere in MapEd (still has a wrong markup display bug. Will be fixed separately)
