### ISSUE TITLE
Trees can be planted on snow

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#120]
Repro steps:

1.- Start the game.
2.- Play a custom map with snow terrain.
3.- Build a and train Woodcutter.

Result: altought apple or corn can't be planted on snowy terrains, trees are planted normally. 

On a related note, "dry earth" is fertile both for trees and crops, and "swampdirt" is fertile for crops but not for trees.

![imagen](https://user-images.githubusercontent.com/36303894/53658708-509fdd00-3c38-11e9-851b-a204b0d83af6.png)

**Comment by Kromster80** [comment]
A. Pine trees on snow are intended behaviour (although I might have to make separate models covered with snow)

B. Cracked Earth issue needs some further thinking )

**Comment by LpTrip** [comment]
I tought so but it felt like inconsistent with the unability to plant apples or corn. 

Following the intended behaviour, 25% snowy terrain doesn't grow pine trees, but regular trees, is that intended too?

**Comment by Klassix** [comment]
Good catch Trip!

**Comment by Kromster80** [comment]
C. "swampdirt" is indeed fertile for crops but not for trees for now. Will need to make 2 different Swamp terrain I guess.
D. 25% snowy terrain does grow pine trees (seen on screen above)

Issue can be closed now. Trees can be planted on snow now )
