### ISSUE TITLE
AI should evaluate ore richness before building a mine

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#121]
As comented on Discord channel, bug report submitted.

![imagen](https://user-images.githubusercontent.com/36303894/53667711-88b31a00-3c50-11e9-9fba-70b9a3262c81.png)

**Comment by Kromster80** [comment]
Another example screenshot by MSK:
![image](https://user-images.githubusercontent.com/4618474/71541275-29509400-295f-11ea-86e9-b690fbe2e0db.png)

**Comment by Kromster80** [comment]
Fixed in Alpha 12 wip.
