### ISSUE TITLE
Coalmaker's smoke emitter remains after destroying building

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#123]
Repro steps:

1.- Start the game.
2.- Grow your town until you have a coalmaker's.
3.- Train a woodcutter and wait until it starts producing coal.
4.- As soon smoke appears in the building, destroy it.

Result: smoke emitter remains on the ground indefinitely.

![imagen](https://user-images.githubusercontent.com/36303894/53905211-b3251e80-4026-11e9-86b5-afca65936f46.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7247
