### ISSUE TITLE
New constructed enemy buildings are shown under fog of war

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#124]
Repro steps:

1.- Start the game and play a map.
2.- Explore enemy town (e.g. with a scout and leave).
3.- See how enemy towns get built under FOW.

Result: you can see enemy's town development under fog of war, altough no unit has visited the town again.

You explored:

![imagen](https://user-images.githubusercontent.com/36303894/53958433-ccc67480-40bf-11e9-9657-2c34f3743c49.png)

But, after some time you see...

![imagen](https://user-images.githubusercontent.com/36303894/53958461-dfd94480-40bf-11e9-91a3-85f044a815b3.png)

**Comment by Kromster80** [comment]
This is a big task that requires rework of players view on terrain/mapobjects/houses/etc

**Comment by Kromster80** [comment]
Fixed by introduction of RealFOW in ~r8150
