### ISSUE TITLE
Blanks can be stored in camp

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#127]
Repro steps:

1.- Start the game.
2.- Build a cottage.
3.- Click to train multiple serfs (i.e. 5 serfs).
4.- Wait for all blanks to enter camp, and fast cancel training (current training must not be completed).

Result: some blanks come back to cottage but others stay inside camp.

![imagen](https://user-images.githubusercontent.com/36303894/54035023-1b930d80-4197-11e9-86dd-966b00000072.png)

**Comment by Kromster80** [comment]
Hopefully fixed in r7935
