### ISSUE TITLE
AI produces coal in a map with no ores to mine

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#131]
Repro steps:

1.- Start the game.
2.- Play the map Crossing with at least one AI.
3.- Continue playing for enough time until it builds a Coalmaker.

Result: although there's no gold or iron to mine, AI produces coal. In spite of building being available for construction, AI should evaluate if it should be built.

![imagen](https://user-images.githubusercontent.com/36303894/54455887-94680b80-473b-11e9-9b55-73c8324825e5.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7625
