### ISSUE TITLE
Blanks places don't get reassigned after destroying a cottage

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#132]
Repro steps:

1.- Start the game and play a map where you have to build base from scratch (i.e Crossing).
2.- Place two cottages at the same time. Images below for description.
3.- As soon first cottage is built, destroy the other one

Result: places don't get reasigned and you get 20 blanks for only one cottage.

![imagen](https://user-images.githubusercontent.com/36303894/54459526-ababf680-4745-11e9-9cf8-1c10b055e741.png)

![imagen](https://user-images.githubusercontent.com/36303894/54459544-b6668b80-4745-11e9-9180-14a42405f7ad.png)

![imagen](https://user-images.githubusercontent.com/36303894/54459556-bc5c6c80-4745-11e9-9c3a-4d1994950631.png)

**Comment by Kromster80** [comment]
Hopefully fixed in r7935
