### ISSUE TITLE
Starting an empty map results in "EAccessViolation at memory address"

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#133]
Repro steps:

1.- Start the game.
2.- Select Map Editor > Create New Map.
3.- Choose any default terrain.
4.- Save the map.
5.- Quit editor, click Single player and try to load the map.

Result: map can't be loaded, returns error shown below.

![imagen](https://user-images.githubusercontent.com/36303894/54461866-9e463a80-474c-11e9-98d3-b9768cbcc707.png)

**Comment by Kromster80** [comment]
Maps with 0 hands can not be started in game mode now.
