### ISSUE TITLE
Skirmish maps can be started with no rivals

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#135]
Repro steps:

1.- Start the game.
2.- Select single player > single map.
3.- Choose any skirmish map (i.e Winter sand). 
4.- Click over Weak AI and change to closed.
5.- Click start map.

Result: game starts and map is won automatically.

![imagen](https://user-images.githubusercontent.com/36303894/54483420-45040700-4831-11e9-84f3-c15b89dad3e7.png)

**Comment by Kromster80** [comment]
Thanks for report!

Removed victory message from when playing Skirmish maps solo.
You still can play solo if you want to
