### ISSUE TITLE
Resize button seems to do nothing when changing map's height

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#139]
Game version: Alpha 11 wip r7289.

Repro steps:

1.- Start the game.
2.- Open MapEd.
3.- Click Menu > Resize map.
4.- Change "Move height level" value.
5.- Click Resize.

Result: nothing seems to be happening, but actually a new map is being created and if you click resize 12 times in a row, you encounter with issue #73. When starting the game once again, you see all maps listed.

**Comment by Kromster80** [comment]
"Move height level" changes the map base-height (which is 30 by default, iirc). So if you need to make a really deep ravine and you hit the bottom and height can't get lower than base - move the height level and you can continue editing the depe ravine

**Comment by LpTrip** [comment]
Yes, I know what's the button for. But if you only change "Move height" level value, and click resize, nothing seems to be happening.

But if in addition to changing height, you also modify map borders, clicking Resize generates a new map.

**Comment by Kromster80** [comment]
Thanks for details!
Fixed
