### ISSUE TITLE
Several wares icons overlap with text in UI

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#140]
Game version: Alpha 11 wip r7289.

For example in Woodcutters house UI, when maxed out, tree trunks icons overlap the text:

![imagen](https://user-images.githubusercontent.com/36303894/54750070-488ee980-4bb5-11e9-88e8-4ef38080ebe3.png)

This issue also occurs with the following wares when maxed out, at any building that consumes or produces said ware:

- Tree trunks
- Stones (only when there are 6 or 7)
- Cowhides
- Sausages
- Iron ore
- Gold ore
- Hand axes
- Longbows
- Wooden shield
- Leather armor
- Crossbow
- Iron armors
- Iron shield.

Gold and leather are _really close_ to text, could have a bit more of space.

**Comment by Kromster80** [comment]
Made text render on top for now.
Hoping to redesign the UI some time later on

**Comment by Kromster80** [comment]
Will close this one. Rendering text on top is sufficient solution.
