### ISSUE TITLE
Team number is not linked to players

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#142]
Game version: Alpha wip 11 r7289

1.- Start the game.
2.- Select a skirmish map and fill all positions with AIs.
3.- Add a different team number for each one, image below for explanation:

![imagen](https://user-images.githubusercontent.com/36303894/54754612-ab3ab200-4bc2-11e9-8bc2-5bbbc4d2f85c.png)

4.- Close 2nd position.

Result: following example above, remaining players should be team 1, 3 and 4, but you have teams 1, 2 and 3.

![imagen](https://user-images.githubusercontent.com/36303894/54754653-c4dbf980-4bc2-11e9-9b27-129702e22133.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7475
