### ISSUE TITLE
Undo doesn't work for roadworks in MapEd

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#143]
Game version: Alpha 11 wip r7289

1.- Start the game.
2.- Open MapEd.
3.- Place several road tiles.
4.- Click undo.

Result: undo doesn't remove road. This issue also occurs with corn fields and apple orchards. Undoing this last two, removes the corn plant and the apple tree.

![imagen](https://user-images.githubusercontent.com/36303894/54839008-b9fb9480-4ca8-11e9-88db-638a66bab886.png)

**Comment by Kromster80** [comment]
Fixed in r8409
