### ISSUE TITLE
Loading a map and trying to add units results in ERangeError: Range check error.

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#153]
Game version: Alpha 11 wip r7658

1.- Start the game.
2.- Click Map Editor > Load existing map.
3.- Select any map and open it.
4.- Click Village planning > Units.
5.- Try to add any unit to the map.

Result: ERangeError message appears. Bug report sent.

![imagen](https://user-images.githubusercontent.com/36303894/61729028-c3773500-ad4c-11e9-81e8-a39aba4127b2.png)

**Comment by Kromster80** [comment]
Fixed in r7659
