### ISSUE TITLE
Nh is shown in game results stats but has no values (units/houses tab)

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#154]
Build: 7690

Repro steps:

1.- Play any map with neutrals (i.e.: Fighting Back)
2.- Let game idle for a while (so there are at least some stats collected) then exit map to Results screen.

Result: Neutral hostile is shown in stats but has no values on any tab.

![imagen](https://user-images.githubusercontent.com/36303894/61952312-e5a9c680-af89-11e9-86a3-46cb81ed6896.png)

**Comment by Kromster80** [comment]
1. Decide if Ni Nh need to be shown at all
2. Fix stats collection for them

**Comment by Kromster80** [comment]
Decided to remove Ni/Nh from results altogether for now. If we ever need them - they can be readded.
