### ISSUE TITLE
Assertion failure (..\units\KM_Unit_Warrior.pas, line 416) when ordering unit to exit tower

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#155]
Build: 7690

Repro steps:

1.- Start any single player map (i.e. Borders)
2.- Grow town until you can train soldiers and build towers.
3.- Build a tower and train 2 soldiers.
4.- Order soldiers to enter tower.
5.- Select tower and order soldier to exit.

Result: assertion appears. Issue seems to be related to soldier staying grouped to other soldier inside tower. This issue affects both types of towers. Bug report sent.

![imagen](https://user-images.githubusercontent.com/36303894/61957123-ea27ac80-af94-11e9-9621-f5a4b7d9bae2.png)

**Comment by Kromster80** [comment]
Hopefully fixed in r7935
