### ISSUE TITLE
Woodcutter fails to plant more trees if his hut is full with trunks

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#161]
Build: 7701

Repro steps:

1.- Start the game
2.- Play a custom map with woodcutter hut and **no serfs**.
3.- Verify that behaviour is set to "Plant and fell".
4.- Wait until woodcutter chops 5 trees.

Result: after woodcutter storage is full, he tries to go out and plant a tree but then he goes back inside, doing nothing. This behaviour repeats until trunks amount lowers to 4 or less.

![imagen](https://user-images.githubusercontent.com/36303894/62823528-1b44d700-bb68-11e9-9ad4-6584d33e78bb.png)

![imagen](https://user-images.githubusercontent.com/36303894/62823584-bb9afb80-bb68-11e9-9fd4-01cdf5222d7e.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7765
