### ISSUE TITLE
Apple trees can be removed, but the fence stays and they grow back

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#162]
Build: 7701

Repro steps:

1.- Start the game.
2.- Play any map.
3.- Lay out an apple orchard.
4.- Select "demolish" and click any apple tree.

Result: laborer removes apple tree, but orchard's fences remain. If you wait for a white, the apple tree appears again.

![imagen](https://user-images.githubusercontent.com/36303894/62823662-99ee4400-bb69-11e9-9893-b66fb119cf68.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7767
