### ISSUE TITLE
Units can access an unbuilt tower

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#164]
Build: 7701

Repro steps:

1.- Start the game
2.- Play any skirmish map.
3.- Build your town until you can have towers.
4.- Train some militia.
5.- Order your laborers to build a tower.
6.- As soon they start digging, select your troop an order to access tower.

Result: units can access the unbuilt tower. They "disappear" but as soon tower is built they "reappear" inside it.

![imagen](https://user-images.githubusercontent.com/36303894/62943944-065b8400-bdb2-11e9-938a-033f3f22dedc.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7791
