### ISSUE TITLE
ERangeError: Range check error on Dusty Day map load

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#166]
Build 7791

Repro steps:

1.- Start the game.
2.- Select Single Player > Single Map > Dusty day. 
3.- Try to play the map:

Result: Error appears.

![imagen](https://user-images.githubusercontent.com/36303894/63112763-6e9f9680-bf67-11e9-91f4-0602152b9a73.png)

**Comment by Kromster80** [comment]
Thanks for report!
Completed: At revision: 7816
