### ISSUE TITLE
Game crashes when playing Man vs Man vs Beast map

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#167]
Built 7791

Repro steps:

1.- Start the game.
2.- Select Single Player Maps and choose Man vs Man vs Beast.
3.- Add 3 AI players, preferably strong AI or better.
4.- Play the map and set game speed to x8.
5.- Idle for a bit or attack wolf dens.

Result: Error messages shown below appear, bug report were sent. Exception with militia appears after clicking resume application on first error, and continues to appear if you click resume.

![imagen](https://user-images.githubusercontent.com/36303894/63113340-b377fd00-bf68-11e9-9d47-b788c2aa3f03.png)

![imagen](https://user-images.githubusercontent.com/36303894/63113345-b7a41a80-bf68-11e9-980e-a46059fa2881.png)

**Comment by Kromster80** [comment]
Fixed a couple of related bugs in r7824
