### ISSUE TITLE
Building's UI overlaps with Store inventory in MapEd

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#168]
Build: 7823

Repro steps:

1.- Start the game.
2.- Open MapEd.
3.- Place any building and click it.

Result: Building UI shows wrong information. Similar bug to Horse distribution overlapping with Steel.

![imagen](https://user-images.githubusercontent.com/36303894/63345406-0c5ce200-c329-11e9-8dbd-0aabe6f2d759.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7860
