### ISSUE TITLE
Placing road over sapling removes the tree but it grows back afterwards

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#169]
Build: 7823

Repro steps:

1.- Start the game
2.- Play any single player map.
3.- Build a woodcutter's hut.
4.- Wait until it plants a tree sapling.
5.- Place a road over the tree.
6.- Fast forward a bit.

Result: after road is placed, it removes the tree but after a while it grows back.

![imagen](https://user-images.githubusercontent.com/36303894/63348606-f56dbe00-c32f-11e9-85e7-8808f4a276b9.png)

**Comment by Klassix** [comment]
Same thing happens when a tree sapling gets placed inside a construction site.

**Comment by Kromster80** [comment]
Fixed in r8556
Trees will remain until chopped.
Fields/Orchards replace saplings/trees.
