### ISSUE TITLE
After dinner, blanks don't go back home.

### ISSUE THREAD

**Issue by Pimwe** [Kromster80/knights_province#17]
In alpha 8.2, blanks do not go back to their cottage after having dinner in the tavern. They just hang around the tavern wondering what to do.

Will update this with a screenshot later.

**Comment by Kromster80** [comment]
Great, thanks for reporting!

**Comment by Pimwe** [comment]
![idleblanks](https://user-images.githubusercontent.com/29592830/27398054-ce83ab96-56b8-11e7-81e5-9bedf9d78971.PNG)

**Comment by Kromster80** [comment]
Fixed in Alpha 9 iirc
