### ISSUE TITLE
Story mode maps with no objectives have some sort of AI

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#171]
Build: 7823

Repro steps:

1.- Start the game.
2.- Create a new custom map.
3.- Add a camp, put stone and wood in it.
4.- Place some serfs and builders.
5.- Save the map and exit MapEd.
6.- Go to Single Player > Single Map and play the recently created map.
7.- Play for a bit, build some cottages, a schoolhouse, woodcutter's hut, etc.

Result: serfs and builders are automatically created, aswell as woodcutter, stonemasons an any other units. Also, if you have towers and train troops, they automatically go to the tower.

This issue does not occur if map has objectives.

**Comment by Kromster80** [comment]
Fixed in r7862
