### ISSUE TITLE
Archers can shoot across mountains

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#172]
Image is self explainatory.

I didn't understand why I was under attack until I explored the other side of the mountain.

![imagen](https://user-images.githubusercontent.com/36303894/63609362-6b328d80-c5ad-11e9-884d-e7f1142981c1.png)

**Comment by Kromster80** [comment]
It would be hard to display to the player a clear rule when archer can and can not shoot across something. For the sake of simplicity I'm going to leave this "as is".
