### ISSUE TITLE
Pre-game minimaps don't show entire map layout

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#173]
Build: 7862

Repro steps:

1.- Open the game.
2.- Click single player > single map.
3.- Choose any skirmish map.

Result: most minimaps only show "explored" areas, instead of showing the entire layout. you can't tell if it has rivers, mountains, ores, etc. I've noticed some Story Type maps show more.

![imagen](https://user-images.githubusercontent.com/36303894/64188655-3219d900-ce49-11e9-9435-f9c2b0dc6fb2.png)

**Comment by Kromster80** [comment]
Made Skirmish maps minimap preview to be always revealed
