### ISSUE TITLE
Unable to build on some tiles

### ISSUE THREAD

**Issue by Pimwe** [Kromster80/knights_province#18]
It is impossible to build on some tiles. I noticed this in Dusty Day, especially west of the starting position. To me it seems the tiles are corrupt or something: I cannot own them, nor walk on them. In the attached screenshot, ownership and passibility are shown. Using the map editor, I tried smoothing the area (didn't help) and repainting the area with grass (didn't help). There are no objects to delete.

If the tiles are made unavailable on purpose, my suggestion would be to add a visual element to make clear the tiles are blocked. For example, some rocks or vegetation.
![nobuilding](https://user-images.githubusercontent.com/29592830/27488869-d934dfac-5838-11e7-8d35-7d338231e4ce.PNG)

**Comment by Pimwe** [comment]
Finally figured it out: there are invisible objects that block the tile. For when anyone else bumps into this: to place the blocking objects go to "Terrain editing" (tree and hill icon) in the map editor, then "Objects" (tree and dot icon). Using the stop sign, the invisible objects are placed, and can be removed with the delete-cross. I think those tiles should be used sparingly. I can imagine some legit cases to use them, but since they are invisible, I find them annoying.

**Comment by Kromster80** [comment]
Thanks for reporting!
I've added "block" object preview in MapEd (will be in Alpha 8.3+).
Also we discussed this with map author, so the map will be fixed too.
