### ISSUE TITLE
SFX can be heard on unexplored map areas

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#180]
Build: 7935

Repro steps:

1.- Ensure to have sound on.
2.- Start the game.
3.- Play any skirmish map.
4.- Place camera on minimap near enemy's location.

Result: you can hear sound effects of enemy town (schoolhouse bell ringing, builders hammering, etc.)

**Comment by Kromster80** [comment]
Completed: At revision: ~8180
