### ISSUE TITLE
Coalmaker's progress bar completes twice before producing coal

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#181]
Build 7935

Repro steps:

1.- Start the game
2.- Play any skirmish map
3.- Build your base and place a Woodcutter's and a Coalmaker.
4.- Wait until Coalmaker recives a tree trunk.

Result: coalmaker progress bar completes twice before producing coal.

![imagen](https://user-images.githubusercontent.com/36303894/66224382-1dc93600-e6ac-11e9-9b56-c9a1c1ea00f5.png)

**Comment by Kromster80** [comment]
Coalmakers job is planned to consist of 2 parts:
 - Firstly he sets up a coal pile and puts it on fire. While it burns out he is free for other things to do.
 - After pile has burned and charcoal is produces, he needs to disassemble the pile and collect the coal.
