### ISSUE TITLE
Tile previously occupied by a stockpile can't be built until ware is stored

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#189]
Build: 7996

Repro steps:

1.- Start the game
2.- Play or create a map with a stockpile (i.e. Roman's Fort)
3.- Have your serfs collect the stockpile
4.- While serf is on route to camp, try to place a building in the tile where previously stockpile was located.

Result: you can't build on the location were stockpile was located, until serf stores the ware.

While serf is on route to camp:
![imagen](https://user-images.githubusercontent.com/36303894/66836418-a612cb00-ef37-11e9-85b2-e0ba224fb648.png)

After stone was stored: 
![imagen](https://user-images.githubusercontent.com/36303894/66836470-c2166c80-ef37-11e9-9ee3-754176b25f8d.png)

**Comment by Kromster80** [comment]
Completed: At revision: 8353
