### ISSUE TITLE
Canceling one unit in school is unclear

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#195]
When training serfs/builders or in school - if you right click it cancels the whole stack. Example - I need 5 farmers, I accidently order 6 farmers, I want to cancel 1, but I can't. If I right click it will cancel all 6, including the one in progress.

**Comment by LpTrip** [comment]
Sorry if this comes from a chat on Discord (haven't been able to read there for a while), but to cancel 1 shouldn't you use LMB instead? RMB is used to cancel 10 and LMB + RMB to cancel 100.

**Comment by Kromster80** [comment]
LMB to the rescue! )
