### ISSUE TITLE
UI doesn't scale with resolution

### ISSUE THREAD

**Issue by Trippley** [Kromster80/knights_province#199]
The current game UI/menu doesn't scale with the selected resolution. With a 4k Monitor the UI scale makes it nearly possible to read the text shown on the screen. 

Current work around is using full screen with FHD.

Having an automatic UI scaler or a slider to adjust the UI scale would be highly appreciated.

**Comment by Kromster80** [comment]
Fixed by adding player-option to upscale UI x2 in Alpha 11 wip r8946.
