### ISSUE TITLE
Suggestion: Food Carriage

### ISSUE THREAD

**Issue by Kistrel** [Kromster80/knights_province#2]
What about adding a specialized civilian unit whose only purpose is to feed warriors (obviously serfs would get the task to feed the troops only if there are no carriages available), maybe that also moves faster than serfs and can feed more than 1 warrior per trip?

It would make feeding warriors, especially far away ones, faster and less disruptive on your town's economy.

**Comment by Kromster80** [comment]
Already in my ideas box associated with "control points" and "caravans", thanks!
