### ISSUE TITLE
EAssertionFailed: Warriors must enter tower in groups of 1 (..\houses\KM_HouseTower.pas, line 212)

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#210]
This issue is really hard to reproduce, I detected it playing a custom map ("Wheel" made easy). Towers were far away from camp, and serfs had to travel a long road to deliver food. So for an easier reproduction of this bug, I created a new custom map, with 3 blanks, 3 tower and 9 bowmen. Explainatory image shown below.

![image](https://user-images.githubusercontent.com/36303894/73481515-bb8ef200-437a-11ea-8ef1-8e0d724791b6.png)

Build: 8578.

1) Start the game.
2) Make the custom map and play it.
3) Order archers to access the towers.
4) When timeplay reachs **exactly** 21:15, train 3 serves.
5) At 22:20, archers will pop out of towers.
6) Quickly, before the starving archer receives food, order other 2 archers leave the tower.

NOTE: it is important that only one archer is outside the tower, if there are 2 issue does not reproduce. A save on minute 19 is recommended for easier reproduction.

Result: assertion appears. After clicking "Resume application", a second assert appears: bowman has no Action at the start of UpdateState. You can't continue after this asserts appears, it keeps showing over and over. Screenshot attached below and bug report sent.

![image](https://user-images.githubusercontent.com/36303894/73481531-c6498700-437a-11ea-8944-a94b81ab3661.png)

![image](https://user-images.githubusercontent.com/36303894/73481550-cfd2ef00-437a-11ea-874a-b0a9d530dc8c.png)

**Comment by LpTrip** [comment]
Videos of bug reproduction: https://we.tl/t-Qlgmi03isy

**Comment by Kromster80** [comment]
Completed: At revision: 8649
