### ISSUE TITLE
Multiple errors when converting New Map to skirmish

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#214]
Build: 8589

Repro steps:

1.- Open the game
2.- Create a new map in Map Editor.
3.- Click Mission settings.
4.- Select skirmish.
5.- Click "apply" on the popup.

Result: error appears. Bug report sent.

![image](https://user-images.githubusercontent.com/36303894/74178464-66749b00-4c1a-11ea-8c7e-168e3304d1cf.png)

![image](https://user-images.githubusercontent.com/36303894/74178224-f36b2480-4c19-11ea-9575-8b57bbcce81c.png)

**Comment by Kromster80** [comment]
Completed: At revision: 8609  

The bug was caused by ALL hands being recreated on an empty map and thus freed object access in render of yore.
