### ISSUE TITLE
Previously explored enemy buildings can't be targeted under FOW

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#215]
Build: 8589

Repro steps:

1.- Start the game.
2.- Play any skirmish map with troops (i.e: Borders).
3.- Have your scout explore enemy town.
4.- Retreat to your base.
5.- Select your scout again and place your camera over enemy's camp.
6.- Right click the building.

Result: you can't target the building and SFX of "prohibited action" is played.

![image](https://user-images.githubusercontent.com/36303894/74184847-464ad900-4c26-11ea-912e-eddcb0c5e335.png)

**Comment by Kromster80** [comment]
Completed: At revision: 8747
