### ISSUE TITLE
AI may not stop playing after being defeated

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#220]
Build: 8589

Repro steps:

1.- Start the game.
2.- Play any skirmish map with 4 or more AI players (i.e. Crossing).
3.- Advance into late game.
4.- Build an army and destroy barracks and camp of a single player.
5.- Observe "destoy N player" objetive being completed.
6.- Go back to your base.

Result: Sometimes, although AI player has been defeated and therefore the objective completed, it will rebuild its barracks/camp causing the objective to be incomplete again.

**Comment by Kromster80** [comment]
Completed: At revision: 8598

**Comment by LpTrip** [comment]
Issue still occurs on build 8651. Evidence attached:

Objective completed (Camp being built)

![image](https://user-images.githubusercontent.com/36303894/76654558-ff644200-6549-11ea-88e0-82be53751873.png)

Objected demarked (Camp completely rebuilt)

![image](https://user-images.githubusercontent.com/36303894/76654588-15720280-654a-11ea-9e05-b2dc108ce923.png)

![image](https://user-images.githubusercontent.com/36303894/76654516-e2c80a00-6549-11ea-8825-aa53e4f2e7cf.png)

**Comment by Kromster80** [comment]
Changed the defeat condition to account not only for complete houses, but also for houses under construction. r8688
