### ISSUE TITLE
Starving soldiers leave towers in groups of one

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#224]
Build: 8651.

Repro steps:

1.- Start the game.
2.- Play any skirmish map.
3.- Build your town until you can train archers.
4.- Train a some of them, for instance, 15 archers.
5.- Build a guardtower.
6.- Fastforward until archers start to starve.
7.- Select the troop and right click on the guardtower.

Result: soldiers leave the tower leaving it empty, also troop is divided into groops of one. Serfs don't feed them.

Entire troop grouped.
![image](https://user-images.githubusercontent.com/36303894/76424630-448c4680-6387-11ea-8d8c-c2bbb172bc71.png)

Troop starting to starve.
![image](https://user-images.githubusercontent.com/36303894/76424844-8917e200-6387-11ea-8e53-f379b63386f7.png)

Empty tower and troop divided into groups of one.
![image](https://user-images.githubusercontent.com/36303894/76425021-d005d780-6387-11ea-919b-4b275914b73c.png)

**Comment by Kromster80** [comment]
It looks like soldiers should not be allowed to crew the tower if they are going to exit it immediately.
Other than that - exiting towers without linking to other groups is okay

**Comment by Kromster80** [comment]
Completed: At revision: 8912
