### ISSUE TITLE
MapEd: height painting tool can not be set to 2x2 / 4x4 and other even sizes

### ISSUE THREAD

**Issue by reyandme** [Kromster80/knights_province#225]
Actual:
size 1 is 1 node
size 2 is 3x3 = 9 nodes
size 3 is 5x5 = 25 nodes

Expected:
size 1 is 1 node
size 2 is 2x2 = 4 nodes
size 3 is 3x3 = 9 nodes

**Comment by Kromster80** [comment]
Fixed in r9692
