### ISSUE TITLE
MapEd UnEqualize does not work on absolutely flat terrain

### ISSUE THREAD

**Issue by reyandme** [Kromster80/knights_province#227]
1. Create new empty map
2. Lower terrain to 0 level on large area
3. try to unequalize inside lowered area. Unqualize will not work there.

Fixed for KMR [here](https://github.com/reyandme/kam_remake/commit/e1dc67523611342afd7639e6acb46dfbe9dc7003)

**Comment by Kromster80** [comment]
Unequalize is not intended to work on absolutely flat terrain - there's nothing to UN-equalize there ;-)

**Comment by reyandme** [comment]
Well, its differs from my point of view. 
Unequalize tool should work for any surface with similar result. Tool result should not differs drastically depending on 1 height, like it is now in KP and was in KMR. Mapmaker could be unaware  if there is 1 height difference or there is none.
But I see you have a different opinion, up to you ;)
