### ISSUE TITLE
Removing a fence blockage on stonemason's hut won't remove pickaxe icon 

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#244]
Build: 8867

Repro steps:

1.- Start the game.
2.- Play any skirmish map.
3.- Build a schoolhouse, a cottage and a stonecutter's.
4.- Place fences around the stonecutter's so it can't reach stone.
5.- Notice that pickaxe icon (no further stone available to pick) will appear.
6.- Destroy the fences.

Result: altough stonemason will return to work, pickaxe icon doesn't disappear.

![image](https://user-images.githubusercontent.com/36303894/79388011-02849080-7f43-11ea-84b6-eafd175cc416.png)

**Comment by Kromster80** [comment]
Completed: At revision: 8871
