### ISSUE TITLE
MapEd: trigger area resize works only in 1 dimension at a time, would be nice to have it in 2 dimensions

### ISSUE THREAD

**Issue by reyandme** [Kromster80/knights_province#299]
Could be started from the corner, or even from any point of 'blue strip'.

https://i.imgur.com/RTVI5e9.gif

Other improvements, mentioned while discussing in discord: 
- mark active blue strips
- use better font

**Comment by Kromster80** [comment]
Would be good to highlight the active areas (edges, corners) on mouse over as well

**Comment by Kromster80** [comment]
Made the triggers resizeable by corners.
Switched to slightly better font.
Other prettifications are not that important yet
