### ISSUE TITLE
Suggestion: food and battle effectiveness

### ISSUE THREAD

**Issue by Kistrel** [Kromster80/knights_province#3]
What about making it so that warriors are most effective when about halfway full?
It would make bread better without actually changing it (assuming that in KP it doesn't just feed to full as in KaM... didn't check) and would make suicide runs from starving troops (instead of just feeding them) a much weaker strategy.

**Comment by Kromster80** [comment]
Not sure if additional layer of complexity is needed in this already complex game. Thanks for idea though.
