### ISSUE TITLE
After building a second Woodcutter hut, it doesn't have animations. This issue only affects this profession.

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#30]

**Comment by Kromster80** [comment]
Please clarify, what animations are missing?

**Comment by Kromster80** [comment]
Looks like this is caused by not all anims being in place. Checked anims and fixed the "carrying plant" anim. Please recheck in r7145+.

**Comment by LpTrip** [comment]
It's still broken, but in a different way. Now animations are mising **after** they fell or plant a tree. 

They walk normally towards the location they are going to work:
![imagen](https://user-images.githubusercontent.com/36303894/51535757-246a9280-1e28-11e9-810f-db108f1bc4a9.png)

Axing the trees animations are OK:
![imagen](https://user-images.githubusercontent.com/36303894/51535737-14eb4980-1e28-11e9-9970-d9b481873b46.png)

But then, as soon the trees starts to fall, animations break:
![imagen](https://user-images.githubusercontent.com/36303894/51535784-3ba98000-1e28-11e9-81ff-1a019cb10571.png)

They "walk" back home completely frozen. This also occurs when they start to plant a tree aswell.

**Comment by Kromster80** [comment]
Okay, this looks like simple case of "Not all unit animations are made yet".

**Comment by Kromster80** [comment]
Not really a bug. New animations will appear in their time later on (in Beta?)
