### ISSUE TITLE
fish and cider tutorial campaign, run out of cider breaks ai

### ISSUE THREAD

**Issue by feelingwalnut** [Kromster80/knights_province#357]
I was trading cider for fish and ran out. at the time my cider houses were not finished and all porters went into a warehouse loop the moment the tavern/inn ran out of stock.
they all were trying to supply cider and would not deliver supplies or collect from facilities to finish construction without closing the inn.

as soon as inn was closed they resumed normal function, reopen and the bug presents itself.

**Comment by Kromster80** [comment]
@feelingwalnut Can you attach savegame/replay files? I can't figure out what was happening

**Comment by feelingwalnut** [comment]
> @feelingwalnut Can you attach savegame/replay files? I can't figure out what was happening

at approximately the 40min mark on the most recent version from the launcher/self updater. not sure if present in previous.
attached is the bundle of "audotave01" related files, not sure which you need.
[autosave01.sav.tar.gz](https://github.com/Kromster80/knights_province/files/13957809/autosave01.sav.tar.gz)

thank you.

**Comment by Kromster80** [comment]
Indeed there was a bug!
Wares taken out of the house were not reported to the Logistics. Hence, when deliveries were asked for, Logistics would offer deliveries that could not be performed due to now missing wares.

I've made a fix, but I'm not sure if there will be another Alpha 12 release soon.

**Comment by feelingwalnut** [comment]
not a big deal, you've been dedicated to all this for so long.
