### ISSUE TITLE
Store doesn't show weapons or equipment inside them.

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#39]

**Comment by LpTrip** [comment]
If you don't have a Fort, but you start producing weapons  and equipment (Axes/Bows, Shields/Leather armors), they are stored in Store (lol) but there is no "icon" for those items on that building and you cannot know how many of those wares you have.

**Comment by Kromster80** [comment]
This is by design. Unless  you have a Fort/Barracks you can not accumulate warfare.
