### ISSUE TITLE
About gold

### ISSUE THREAD

**Issue by Kistrel** [Kromster80/knights_province#4]
Have you thought about what Gold could be used for in KP?
If not, what about making it so that Gold could be (optionally) used for instantaneous civilian training?
(Maybe in a School analogue, some sort of Treasury, which would also act as a storage for Gold.)
It should give a reason to mine and stockpile it, thus making it possible to pump out huge amounts of Recruits in a short amount of time, in case you want to put up a fast defence or have made a town that is constantly about to starve (which would make stockpiling Recruits or Warriors unviable).

**Comment by Kromster80** [comment]
It is likely to be viewed in reverse - you can hire anyone for gold immediately (default), or save gold and wait for hire (when you ran out of gold). Not sure if that is going to be an improvement or not.
