### ISSUE TITLE
Residents inside cottages are starving (some of them die when they go out)

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#40]

**Comment by Kromster80** [comment]
Need better description. Did you have enough food, did you have enough free Tavern spots?

**Comment by LpTrip** [comment]
I was playing campaign and game was about 2 and a half hours. I had plenty of food in Tabern, I didn't know if it had free spots as you can't know for sure at the moment, but I think it did. 

I started mass producing soldiers and noticed that "Blanks" died as soon they left the Cottage and many of them walked to Fort with Hunger symbol above their heads. 

Now that I'm thinking, I've been playing about 10-12 hours the game and I've never saw a "Blank" leaving Cottage to feed in Tabern.

**Comment by LpTrip** [comment]
![imagen](https://user-images.githubusercontent.com/36303894/50696254-b64b6080-101d-11e9-983e-1fa983b9d270.png)

Screenshot for clarification

**Comment by Kromster80** [comment]
Duplicate of #96 (which is shorter description)
