### ISSUE TITLE
Porters loose stone when going out of the Camp doors on to tile without road when delivering to house building site

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#51]
Complicated issue caused by pathfinding and returning to walkable road network ..

**Comment by LpTrip** [comment]
This issue still occurs on build 7658. Happens with wood planks aswell.

**Comment by Kromster80** [comment]
Yep, it's still "Open" (

**Comment by LpTrip** [comment]
Possible quickfix: forcing adjacent roads to Camp's entry to always have a road?

**Comment by Kromster80** [comment]
Thats the plan for now. Already "fixed" Walkers map in such a way )

**Comment by Kromster80** [comment]
Changed delivery destination to the house building site entrance ()which fixes pathing). Porters will drop ware earlier if they touch the building site.
