### ISSUE TITLE
Add a directional arrow showing which way a unit will face on the tile you send them to when you give them a move-to command in the map editor

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#58]

**Comment by DarkianMaker** [comment]
How dare you not credit me for my suggestion :stuck_out_tongue:

**Comment by Kromster80** [comment]
![kp_2022-04-18_21-36-27](https://user-images.githubusercontent.com/4618474/163857212-d7c10fc1-0d46-4cdc-b0fc-d20c283957a5.png)
