### ISSUE TITLE
Warning message at Prologue mission in Orthalm campaign

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#60]
At the beggining of the first mission, a Warning message appears: 

`ct_WareOutAddToLast cannot add goldore to camp @5:103`

![imagen](https://user-images.githubusercontent.com/36303894/50704631-d5a2b780-1036-11e9-9365-fb29a84b05ec.png)

**Comment by Kromster80** [comment]
Fixed in r7130+
