### ISSUE TITLE
Completing additional objective on "Home" mission of Orthalm campaign doesn't grant extra soldiers

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#62]
After completing the additional objetive (build 2 woodcutters, 3 farm, 2 cider makers), nothing happens. According to a message display, you should get extra soldiers.

![imagen](https://user-images.githubusercontent.com/36303894/50725312-9c238800-10da-11e9-8146-923d2c4412ea.png)

**Comment by LpTrip** [comment]
This issue also occurs on mission "First steps", after 1 hour and 10 minutes of play, you receive a message of your steward anouncing reinforcements, but nothing happens.

**Comment by Kromster80** [comment]
Was a bug in dynamic script handling
Completed: At revision: 7144
