### ISSUE TITLE
Pikeman and lancers don't have bonus attack vs mounted units.

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#63]
Created a custom map, 25 lancers vs 25 scouts, and 25 pikeman vs 25 knights. 

![imagen](https://user-images.githubusercontent.com/36303894/50727929-2c74c380-1101-11e9-83e8-3e4f3af0d0dc.png)

The outcome was equal: only 1 scout died, but all lancers and pikeman perished.

![imagen](https://user-images.githubusercontent.com/36303894/50727934-46aea180-1101-11e9-9992-a102e166a201.png)

Retryed several times, sometimes also a knight dies but the result to the fight always is 25-1

**Comment by Kromster80** [comment]
Will be improved in r7180+
