### ISSUE TITLE
With game paused, you can move around by clicking on minimap

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#65]
You can't move using WASD keys or moving cursor to the edges, but you can click on the minimap.

**Comment by Kromster80** [comment]
Please describe the bug in more detail. Can not reproduce it

**Comment by LpTrip** [comment]
I don't kwow why, I can't seem to be able to reproduce it myself aswell. But I did back then 🤔

**Comment by Kromster80** [comment]
I could reproduce similar behaviour when I pressed "p" while dragging Minimap panel - it went on top of Pause overlay.

**Comment by LpTrip** [comment]
I've managed to reproduce it. This are repro steps:

1.- Start a game.
2.- Click on the gray header of the minimap, here:

![imagen](https://user-images.githubusercontent.com/36303894/50858675-d9ed0e80-136f-11e9-8c67-7ed781dc496a.png)

3.- Pause the game. You'll notice that minimap is "active".
4.- Click anywhere on the minimap.

**Comment by Kromster80** [comment]
Same happens if you clicked minimap or other frames during gameplay.
Fix is underway ..

**Comment by Kromster80** [comment]
Fixed in r7141
