### ISSUE TITLE
Game crashes when changing Horses distribution

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#70]
Exception occured: ERangeError: Range check error.

Repro steps:

1.- Start a game on map
2.- Go to distribution menu
3.- Change value on Horses

Couldn't send bug report, got a busy server message.

![imagen](https://user-images.githubusercontent.com/36303894/50861375-369ff780-1377-11e9-8561-67502873fbae.png)

**Comment by Kromster80** [comment]
Fixed in r7136
