### ISSUE TITLE
Critical error when trying to delete a map twice

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#72]
Repro steps:

1.- Open the game
2.- Click Map Editor
3.- Select any map and click delete
4.- Click delete again.

You get error message: Exception occured: ERangeError: Range check error. Bug report was sent.

![imagen](https://user-images.githubusercontent.com/36303894/50982500-16d61400-14dc-11e9-8d14-11a34eb0723c.png)

**Comment by Kromster80** [comment]
Fixed in r7138
