### ISSUE TITLE
Game crashes when resizing a map with a really long name

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#73]
Repro steps:

1.- Open the game.
2.- Click Map Editor.
3.- Create a New Map.
4.- Click Menu > Resize map.
5.- Change values on borders and click Resize.
6.- Repeat steps 4 and 5 several times.

You get error message: Exception occurred: EInOutError: Invalid file name - %s. Bug report was sent. You can't continue playing if you click resume application.

**Comment by Kromster80** [comment]
Likely solution is to change mapname template to a shorter one, e.g. mapname_2.

Also look into why this is breaking further usage.

**Comment by LpTrip** [comment]
I'd like to suggest a solution: don't force the game to save a resized map. Keep it unsaved until user chooses otherwise.

**Comment by Kromster80** [comment]
Hmm.. that's more complicated, but is much more user-friendly. Especially the undo/redo support. Gotta think about it, thanks for suggestion! )

**Comment by Kromster80** [comment]
Decided to fix this an easy way - detect and write down resized mapname as "MapName (Resized##)".

**Comment by Kromster80** [comment]
Completed: At revision: 7858
