### ISSUE TITLE
Woodcutters wrigly indicate there are no trees to fell around

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#74]
![image](https://user-images.githubusercontent.com/4618474/51054853-c697a880-15e6-11e9-8a71-3ad49349506f.png)

**Comment by phoe** [comment]
[saves.zip](https://github.com/Kromster80/knights_province/files/2750887/saves.zip)

**Comment by Kromster80** [comment]
The tree is indeed outside of Woodcutters work range (of 10 tiles)
![image](https://user-images.githubusercontent.com/4618474/51057548-9ce27f80-15ee-11e9-9b38-55aeb7206569.png)

**Comment by phoe** [comment]
I would nonetheless classify this as an issue - the distance calculation algorithm is not obvious and captures trees that grow eight or nine tiles in front of the house but misses trees that are four tiles behind the house.

![zrzut ekranu z 2019-01-11 21-33-59](https://user-images.githubusercontent.com/15045546/51058394-e5973a00-15e8-11e9-93c0-933a8b50d849.png)
