### ISSUE TITLE
Goal is added in MapEd despite user saves it or not

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#78]
Repro steps:

1.- Start the game, open MapEd
2.- Press "Player Settings" button
3,- In "Goals", press add.
4.- Press cancel on the goal/objective.

A goal is added despite choosing "cancel". This can be repeated as many times as desired.

![imagen](https://user-images.githubusercontent.com/36303894/51640515-70a9f580-1f42-11e9-8c08-6e2e69cc30bc.png)

**Comment by Kromster80** [comment]
fixed. thanks!
