### ISSUE TITLE
"Wares" statistics shows wrong information after playing a game with custom AI names

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#79]
Repro steps:

1.- Start the game and play any game with Custom AI names (i.e.: any Fall and Rise of Orthalm campaign map or Alpha1 map).
2.- Play for a few minutes and quit the mission.
3.- Go back to main menu and start a new game in Single Player mode on any map (i.e.: Hodor map).
4.- Quit the mission and click on "Wares" statistics tab.

Result: although it says "No data" on the center of the graph, you can see names and information of the first mission.

![imagen](https://user-images.githubusercontent.com/36303894/51787423-8c82e680-2150-11e9-9fdf-6f461baed0d1.png)

In "Statistics", "Economy" and "Army" the information is correct.

![imagen](https://user-images.githubusercontent.com/36303894/51787450-f13e4100-2150-11e9-9902-87a5be863ccb.png)

**Comment by Kromster80** [comment]
Could not reproduce it after several attempts
