### ISSUE TITLE
Objects near borders multiply when resizing map

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#80]
Repro steps:

1.- Start the game and create a new 16x16 map in MapEd.
2.- Go to Village planning > Houses.
3.- Place corn fields on the west edge and apple orchards on the north edge.

![imagen](https://user-images.githubusercontent.com/36303894/51787723-11bbca80-2154-11e9-85a6-21a1983d9c78.png)

4.- Click Menu > Resize map.
5.- Move west and north borders by 10.

Result: Apple trees and corn fields multiply as far the extension goes. This issue also occurs with Decals (stones, piers, etc.) and objects (trees, mushrooms, etc.). Also occurs with waterbeds and mountains, but I don't know if this last is intended.

![imagen](https://user-images.githubusercontent.com/36303894/51787750-770fbb80-2154-11e9-9f3c-12275561d058.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7198  

Repeating of other terrain features is intended.
