### ISSUE TITLE
Replays don't end

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#81]
Repro steps:

1.- Start the game and play any mission.
2.- Let a few minutes go by and quit.
3.- Click on Watch replay.
4.- Observe the replay (I did in x2) and let time "finish".

Result: replay doesn't stop and furthermore, the game continues as if you were playing :open_mouth: 

![imagen](https://user-images.githubusercontent.com/36303894/51787932-40d33b80-2156-11e9-9641-fc764ab95fe9.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7199

**Comment by LpTrip** [comment]
This issue still occurs. 

There's an option to "continue watching" after replay ended, and game goes by as if it weren't a replay.

![imagen](https://user-images.githubusercontent.com/36303894/53216480-783ce700-3633-11e9-9418-56b985cc6f28.png)
