### ISSUE TITLE
Warning message in MapEd not readeable 

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#82]
Repro steps:

1.- Start the game and open MapEd.
2.- Place player 1 and player 2 camp's with serfs and builders.
3.- On Player Types, deselect "Human" for player 2.
4.- Try to save the map.

Result: a warning message appears but it's truncated

![imagen](https://user-images.githubusercontent.com/36303894/51836441-31332e80-22df-11e9-8c8a-8a1f50c6b136.png)

**Comment by Kromster80** [comment]
Completed: At revision: 7197
