### ISSUE TITLE
Please add a confirmation before deleting maps

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#83]
I've accidentally deleted some maps :disappointed:

**Comment by Kromster80** [comment]
On a sidenote, maps should get deleted to Windows Recycle Bin and should be restorable from it.

**Comment by LpTrip** [comment]
Yeah, they go to recycle bin! Yet is quite annoying to be copying those folders back to game folder.

**Comment by Kromster80** [comment]
Added dialog on deleting a map in MapEd menu
Changed dialog on deleting a savegame to a new common one
Made savegames deletion to place them into Recycle Bin (so they could be restored if deleted by accident)

Fixed in r7189
