### ISSUE TITLE
Game crashes when adding several fog revealers

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#84]
Repro steps:

1.- Start the game and open MapEd.
2.- Place a camp and some serfs.
3.- Set fog revealer size to 64 and place A LOT of them.
4.- Save the map and close MapEd.
5.- Go to single player maps and try to start game.

Result: Game crashed with Exception occured: ERangeError: Range check error. Bug report was sent.

![imagen](https://user-images.githubusercontent.com/36303894/51837967-bddfeb80-22e3-11e9-91a9-18ea4da48c64.png)

**Comment by Kromster80** [comment]
Fixed in r7185+
