### ISSUE TITLE
EAssertionFailed: Assertion failure (..\units\KM_UnitGroups.pas, line 1630)

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#85]
Created a custom map, to see how AI behaves in long term. This is the map:

Map: [AI Long Term Test play.zip](https://github.com/Kromster80/knights_province/files/2807384/AI.Long.Term.Test.play.zip)

When I came back to check, game had crashed with Exception occured: EAssertionFailed: Assertion failure (C:\Users\Krom\Desktop\Delphi\knights_province.svn\src\units\KM_UnitGroups.pas, line 1630). Save game attached and crash report sent.

![imagen](https://user-images.githubusercontent.com/36303894/51904947-c0534b80-239e-11e9-86d1-937f88d4b85f.png)

Savefile: [crashreport.zip](https://github.com/Kromster80/knights_province/files/2807381/crashreport.zip)

Oddly, I had an issue with this same game before, at some point around 1 hour and a half playing, I couldn't build anything because layouts would remove themselves from the ground as soon as I clicked and laborers tryed to perform the task. I have a different savefile for that if you want to check!

**Comment by LpTrip** [comment]
This crash happened again in build 7289. Bug report sent.

**Comment by Kromster80** [comment]
The crash did not repeat since last year, so I'm closing the issue. In case it reappears - there will be a crashreport.
