### ISSUE TITLE
Game results stats are carried over from last game if new one didn't filled them

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#92]
play a quickmatch right after playing DarkianMaker campaign and player names in results are wrong/old

**Comment by Kromster80** [comment]
Could not reproduce. Also the game is recreated on starting a new mission, I can not see how player names could stay old.

**Comment by LpTrip** [comment]
Reproduced on build 7678. 

Issue appears on tab "Wares". Below you can see an image of a quickmatch on Crossing and wares statistics still show Campaign players.

Do you need repro steps?

![imagen](https://user-images.githubusercontent.com/36303894/61876623-b466c300-aec3-11e9-902f-061f25fee91b.png)

**Comment by Kromster80** [comment]
Ah, so it is the wares page that didn't get cleared!

**Comment by Kromster80** [comment]
Completed: At revision: 7692
