### ISSUE TITLE
Autosave generates lots of trash files in recycle bin

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#93]
Repro steps:

1.- Open KP r7196.
2.- Start any game.
3.- Press F8 and let time go by.
4.- Go to recycle bin on Windows.

Result: oldest save goes to recycle bin when replaced by a new one, generating a lot of files in the bin.

![imagen](https://user-images.githubusercontent.com/36303894/52585075-9411e300-2e12-11e9-94cf-43c3362afaf4.png)

**Comment by Kromster80** [comment]
This is a bug indeed. Autosaves should be discarded without going to the Bin. 
Thanks for reporting! )

**Comment by Kromster80** [comment]
Fixed in r7213
