### ISSUE TITLE
Blanks are not leaving their houses to eat

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/knights_province#96]
reported by David:
I’ve noticed that on a tutorial mission, where they left their homes just to die of starvation at the doorstep.

**Comment by LpTrip** [comment]
Isn't this issue the same as #40 ?

**Comment by Kromster80** [comment]
Looks like so. I'll close the #40 since this one is more descriptive

**Comment by Kromster80** [comment]
Fixed in r7216
