### ISSUE TITLE
Weapons appear under map when approaching units to edges

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#98]
Repro steps:

1.- Start a game (i.e: Orthals campaign Prologue).
2.- Select a group of crossbowmen.
3.- Go to lower west corner of the map.

Result: swords appear floating under the map. This issue also occurs with Bowmen, Lance carriers and Pikemen.

Bowmen

![imagen](https://user-images.githubusercontent.com/36303894/52900101-bc159380-31d0-11e9-9f31-6163d185d8b7.png)

Crossbowmen

![imagen](https://user-images.githubusercontent.com/36303894/52900043-05191800-31d0-11e9-9206-550388f4db99.png)

Lance carriers

![imagen](https://user-images.githubusercontent.com/36303894/52900104-cb94dc80-31d0-11e9-982e-c1a34fa75ce0.png)

Pikemen

![imagen](https://user-images.githubusercontent.com/36303894/52900077-51fcee80-31d0-11e9-96b0-7b554c812330.png)

**Comment by Kromster80** [comment]
This also happens for all units that use tools interchangeably. Planned fix is to move all tools into rig items.

**Comment by Kromster80** [comment]
Weapons moved further down to -999
