### ISSUE TITLE
Troop's captain doesn't move in MapEd

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#99]
Repro steps:

1.- Start the game.
2.- Create a new map in MapEd.
3.- Click Village planning > units.
4.- Select any soldier.
5.- Add units and columns.
6.- Right click anywhere to move the troop.

Result: captain of the troop remains in the original spot, causing confusion if the troop actually moved or not (it does). Also, you can place a second unit over captain (i.e you had a troop of axemen, moved it and placed a bowmen in the same spot) and it becomes unselectable.

![imagen](https://user-images.githubusercontent.com/36303894/52900250-75289d80-31d2-11e9-8a32-b334ff2fb91d.png)

**Comment by Kromster80** [comment]
Fixed in r7215
